"use client";
import {useEffect,useRef,useState,type CSSProperties,type ReactNode} from "react";
import dynamic from "next/dynamic";
import {TyperHeading} from "@/components/agency/TyperHeading";
import {AnimatePresence,motion,useMotionValue} from "motion/react";

type Lang="it"|"en";

const AgencyBlurHero = dynamic(() => import("@/components/agency/AgencyBlurHero").then(module => module.AgencyBlurHero));

const copy={
it:{title:<>Siti che fanno sembrare<br/><em>serio</em> il tuo lavoro.</>,intro:"Strategia, design e sviluppo per piccole attività e professionisti che meritano una presenza online più credibile, chiara e memorabile.",cta:"Raccontami il progetto",work:"Vedi come lavoro",ticker:["Siti vetrina","Redesign","Landing page","UX/UI","Sviluppo custom","Supporto umano"],problem:"Un sito credibile parte da cose concrete.",problemText:"Parli direttamente con chi progetta e sviluppa. Prima di iniziare definiamo obiettivi, pagine, tempi e costo; durante il lavoro vedi le scelte e puoi valutarle.",services:"Cosa posso costruire per te",process:"Ecco come funziona.",proof:"Cosa ricevi davvero",faq:"Prima di scrivermi",final:"Hai un’attività valida. Facciamola apparire tale."},
en:{title:<>Websites that make your work<br/>look <em>serious.</em></>,intro:"Strategy, design and development for small businesses and professionals ready for a clearer, more credible and memorable online presence.",cta:"Tell me about it",work:"See the process",ticker:["Showcase sites","Redesign","Landing pages","UX/UI","Custom development","Human support"],problem:"A credible website starts with concrete things.",problemText:"You speak directly with the person designing and building your website. Before work begins, we define goals, pages, timing and cost; throughout the project, you can see and review every decision.",services:"What I can build for you",process:"Here’s how it works.",proof:"What you actually receive",faq:"Before you write",final:"You have a solid business. Let’s make it look that way."}}

const serviceCards=[
{n:"01",title:{it:"Un sito tutto nuovo.",en:"A brand-new website."},text:{it:"Struttura, interfaccia e sviluppo responsive. Fino a 5 pagine, modulo contatti e ti facciamo trovare su Google.",en:"Structure, interface and responsive development. Up to 5 pages, a contact form and the essentials to help people find you on Google."},price:"€400*"},
{n:"02",title:{it:"Recuperiamo il recuperabile.",en:"We’ll salvage what we can."},text:{it:"Diamo una sistematina al tuo sito attuale. Se è umanamente possibile.",en:"We’ll tidy up your current website. If it is humanly possible."},price:"€300*"},
{n:"03",title:{it:"Sito a singola pagina.",en:"A single-page website."},text:{it:"Chiamata anche Landing page. L’essenziale.",en:"Also known as a landing page. Just the essentials."},price:"€250*"},
];

export function AgencyPage({lang,modeControl,languageControl}:{lang:Lang;modeControl:ReactNode;languageControl:ReactNode}){const t=copy[lang];const[quoteOpen,setQuoteOpen]=useState(false);const[revealed,setRevealed]=useState(false);const[pastHero,setPastHero]=useState(false);useEffect(()=>{let frame=0;const update=()=>{frame=0;const hero=document.querySelector<HTMLElement>(".studio-cycle-hero");setPastHero(Boolean(hero&&hero.getBoundingClientRect().bottom<=0))};const onScroll=()=>{if(!frame)frame=requestAnimationFrame(update)};update();addEventListener("scroll",onScroll,{passive:true});addEventListener("resize",onScroll);return()=>{removeEventListener("scroll",onScroll);removeEventListener("resize",onScroll);cancelAnimationFrame(frame)}},[]);const reveal=()=>{setRevealed(true);requestAnimationFrame(()=>setTimeout(()=>document.querySelector(".studio-services")?.scrollIntoView({behavior:"smooth",block:"start"}),80))};return <div className="studio-page">
  <AgencyBlurHero lang={lang} onQuote={()=>setQuoteOpen(true)} onExplore={reveal}/>
  <aside className={`studio-post-hero-actions ${pastHero?"is-visible":""}`} aria-hidden={!pastHero}>
    <button className="studio-post-hero-start" onClick={()=>setQuoteOpen(true)} tabIndex={pastHero?0:-1}>{lang==="it"?"Iniziamo!":"Let’s start!"}</button>
    <div className="studio-post-hero-language">{languageControl}</div>
  </aside>
  <div className={`studio-reveal ${revealed?"is-visible":""}`} aria-hidden={!revealed}>
  <section className="studio-section studio-services"><header><h2>{t.services}</h2></header><StackedServices lang={lang}/><p className="studio-service-disclaimer">{lang==="it"?"Salvo imprevisti. Non ce ne dovrebbero essere.":"Barring surprises. There shouldn’t be any."}</p></section>
  <div className="studio-ticker" aria-hidden><div>{[...t.ticker,...t.ticker].map((x,i)=><span key={i}>{x}<b>✦</b></span>)}</div></div>
  <WebsiteShowcase lang={lang}/>
  <section className="studio-section studio-process" id="process"><header><h2>{t.process}</h2></header><div className="liquid-process-grid"><svg className="liquid-process-defs" aria-hidden><defs><filter id="studio-process-liquid" x="-30%" y="-30%" width="160%" height="160%" colorInterpolationFilters="sRGB"><feGaussianBlur in="SourceGraphic" stdDeviation="8" result="blur"/><feColorMatrix in="blur" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 25 -10"/></filter></defs></svg><ProcessCard n="01" tag={lang==="it"?"Ci parliamo.":"Let’s talk."} title={lang==="it"?"Ci capiamo.":"We understand each other."} text={lang==="it"?"Obiettivi, pubblico e cosa deve fare davvero il sito. Decidiamo il pacchetto (e il prezzo) giusto per te.":"Goals, audience and what the website actually needs to do. We choose the right package (and price) for you."}/><ProcessCard n="02" tag="Demo" title={lang==="it"?"Via ai lavori":"Work begins"} text={lang==="it"?"Architettura, testi e interfaccia. Hai due revisioni totali incluse nel prezzo.":"Structure, copy and interface. Two rounds of revisions are included in the price."}/><ProcessCard n="03" tag="Live" title={lang==="it"?"Sito pronto":"Website ready"} text={lang==="it"?"Codice veloce, responsive e semplice da mantenere.":"Fast, responsive code that stays easy to maintain."}/></div></section>
  <section className="studio-problem"><div className="studio-problem-copy"><h2>{t.problem}</h2><p>{t.problemText}</p></div><div className="studio-stats"><AnimatedStat value={1} pad="2" label={lang==="it"?"referente, dall’inizio alla consegna":"contact, from kickoff to handoff"}/><AnimatedStat value={3} pad="2" label={lang==="it"?"momenti chiari: brief, design e consegna":"clear stages: brief, design and handoff"}/><AnimatedStat value={0} pad="2" label={lang==="it"?"costi aggiunti senza approvazione":"added costs without approval"}/></div></section>
  <section className="studio-proof"><h2>{t.proof}</h2><div>{(lang==="it"?[["Design approvato","Vedi pagine e contenuti prima che inizi lo sviluppo"],["Codice e accessi","Il sito e gli account del progetto restano tuoi"],["Consegna guidata","Istruzioni essenziali e supporto post-lancio definiti nel preventivo"]]:[["Approved design","You review pages and content before development begins"],["Code and access","The website and project accounts remain yours"],["Guided handoff","Essential instructions and post-launch support defined in the proposal"]]).map((x,i)=><article key={i}><strong>{x[0]}</strong><p>{x[1]}</p></article>)}</div></section>
  <section className="studio-faq"><header><h2>{t.faq}</h2></header>{(lang==="it"?[{q:"Quanto costa?",a:"Dipende dalla complessità. Dopo una prima call ricevi una proposta chiara, con prezzo e tempi definiti."},{q:"Quanto tempo serve?",a:"Una landing richiede in genere 1–2 settimane; un sito completo 3–5 settimane."},{q:"Lavori anche con un sito già esistente?",a:"Sì. Posso intervenire con un redesign completo o migliorare soltanto le parti che frenano il progetto."},{q:"Poi resto da solo?",a:"No. Consegna guidata, documentazione essenziale e un periodo di supporto post-lancio definito nel preventivo."}]:[{q:"How much does it cost?",a:"It depends on complexity. After an initial call, you receive a clear proposal with defined timing and price."},{q:"How long does it take?",a:"A landing page usually takes 1–2 weeks; a complete website takes 3–5 weeks."},{q:"Can you work on an existing site?",a:"Yes. I can redesign it completely or improve only the parts holding the project back."},{q:"Am I left alone after launch?",a:"No. You receive a guided handoff, essential documentation and a post-launch support period defined in the proposal."}]).map((f,i)=><Faq key={i} {...f}/>)}</section>
  <footer className="studio-final"><span>PRR / STUDIO</span><TyperHeading text={t.final}/><button className="squircle-control studio-final-cta" onClick={()=>setQuoteOpen(true)}><span>{t.cta}</span><i className="studio-cta-arrow" aria-hidden/></button><div className="studio-final-contact-actions"><a href="mailto:pirruccio.01@gmail.com"><i className="fa-solid fa-envelope"/><span>Mail</span></a><a href="https://tidycal.com/paolopirruccio"><i className="fa-solid fa-calendar-check"/><span>{lang==="it"?"Prenota":"Book"}</span></a></div><div className="studio-footer-mode-switch">{modeControl}{languageControl}</div><div className="studio-final-meta"><p>© {new Date().getFullYear()} Paolo Pirruccio</p><p>{lang==="it"?"Italia":"Italy"} · Remote friendly</p></div></footer></div>
  {quoteOpen&&<RedesignWizard lang={lang} onClose={()=>setQuoteOpen(false)}/>}
  </div>}

const wizardQuestions={
  it:[{title:"Da dove partiamo?",options:[["Ho già un sito",0],["Parto da zero",80]]},{title:"Quanto è grande?",options:[["Una landing page",0],["Fino a 5 pagine",140],["Più di 5 pagine",280]]},{title:"Cosa serve davvero?",options:[["Un restyling visivo",0],["Struttura e testi",120],["Strategia completa",220]]},{title:"Quando vuoi partire?",options:[["Senza fretta",0],["Entro un mese",70],["Il prima possibile",140]]}],
  en:[{title:"Where are we starting?",options:[["I already have a website",0],["Starting from scratch",80]]},{title:"How large is it?",options:[["One landing page",0],["Up to 5 pages",140],["More than 5 pages",280]]},{title:"What do you really need?",options:[["A visual refresh",0],["Structure and copy",120],["Complete strategy",220]]},{title:"When should we start?",options:[["No rush",0],["Within a month",70],["As soon as possible",140]]}],
} as const;

function RedesignWizard({lang,onClose}:{lang:Lang;onClose:()=>void}){
  const[step,setStep]=useState(0);const[answers,setAnswers]=useState<{label:string;value:number}[]>([]);const[name,setName]=useState("");const[email,setEmail]=useState("");
  const questions=wizardQuestions[lang],done=step===questions.length,total=290+answers.reduce((sum,item)=>sum+item.value,0);
  const choose=(label:string,value:number)=>{setAnswers(prev=>[...prev.slice(0,step),{label,value}]);setStep(step+1)};
  const summary=answers.map((answer,index)=>`${index+1}. ${answer.label}`).join("%0A");
  const mail=`mailto:pirruccio.01@gmail.com?subject=${encodeURIComponent(lang==="it"?"Richiesta redesign guidata":"Guided redesign request")}&body=${lang==="it"?"Ciao Paolo, ecco il mio brief:":"Hi Paolo, here is my brief:"}%0A%0A${summary}%0A%0A${encodeURIComponent(`Nome: ${name}\nEmail: ${email}\nStima visualizzata: €${total}–€${total+120}`)}`;
  const transition={duration:.42,ease:[.22,1,.36,1] as [number,number,number,number]};
  return <div className="studio-wizard-backdrop" role="presentation" onMouseDown={event=>event.target===event.currentTarget&&onClose()}>
    <motion.section layout transition={{layout:transition}} className="studio-wizard" role="dialog" aria-modal="true" aria-label={lang==="it"?"Preventivo guidato":"Guided estimate"}>
      <header><span>PRR / QUICK ESTIMATE</span><button onClick={onClose} aria-label={lang==="it"?"Chiudi":"Close"}>×</button></header>
      <div className="studio-wizard-progress"><i style={{width:`${Math.min(100,(step/questions.length)*100)}%`}}/></div>
      <AnimatePresence mode="wait" initial={false}>
        {!done?<motion.div className="studio-wizard-step wizard-morph-panel" key={`step-${step}`} initial={{opacity:0,filter:"blur(18px)",scale:.965,y:18,borderRadius:38}} animate={{opacity:1,filter:"blur(0px)",scale:1,y:0,borderRadius:24}} exit={{opacity:0,filter:"blur(15px)",scale:1.025,y:-12,borderRadius:44}} transition={transition}>
          <small>{String(step+1).padStart(2,"0")} / {String(questions.length).padStart(2,"0")}</small><h2>{questions[step].title}</h2>
          <div>{questions[step].options.map((option,index)=><motion.button initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{...transition,delay:index*.045}} key={option[0]} onClick={()=>choose(option[0],option[1])}><span>{option[0]}</span><b>↗</b></motion.button>)}</div>
          {step>0&&<button className="wizard-back" onClick={()=>setStep(step-1)}>← {lang==="it"?"Indietro":"Back"}</button>}
        </motion.div>:<motion.div className="studio-wizard-result wizard-morph-panel" key="result" initial={{opacity:0,filter:"blur(22px)",scale:.94,borderRadius:48}} animate={{opacity:1,filter:"blur(0px)",scale:1,borderRadius:24}} exit={{opacity:0,filter:"blur(16px)",scale:1.03,borderRadius:48}} transition={transition}>
          <small>{lang==="it"?"STIMA INDICATIVA":"INDICATIVE ESTIMATE"}</small><h2>€{total}–€{total+120}</h2><p>{lang==="it"?"Prezzo di lancio orientativo. Prima di iniziare confermo sempre perimetro, tempi e costo finale.":"Indicative launch price. Scope, timing and final cost are always confirmed before work starts."}</p>
          <div className="wizard-contact"><input value={name} onChange={e=>setName(e.target.value)} placeholder={lang==="it"?"Il tuo nome":"Your name"}/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><a href={mail}>{lang==="it"?"Invia il brief":"Send the brief"} ↗</a></div><button className="wizard-back" onClick={()=>setStep(0)}>← {lang==="it"?"Ricomincia":"Start again"}</button>
        </motion.div>}
      </AnimatePresence>
    </motion.section>
  </div>
}

function Faq({q,a}:{q:string;a:string}){const[open,setOpen]=useState(false);return <button className="studio-faq-row" onClick={()=>setOpen(!open)} aria-expanded={open}><span>{q}</span><b>{open?"−":"+"}</b><i className={open?"open":""}>{a}</i></button>}

function AnimatedStat({value,label,suffix="",pad}:{value:number;label:string;suffix?:string;pad?:string}){const host=useRef<HTMLElement>(null);const[count,setCount]=useState(0);useEffect(()=>{const node=host.current;if(!node)return;const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;if(reduced){setCount(value);return}let frame=0;const observer=new IntersectionObserver(([entry])=>{if(!entry.isIntersecting)return;observer.disconnect();const start=performance.now(),duration=950;const tick=(now:number)=>{const progress=Math.min(1,(now-start)/duration),eased=1-Math.pow(1-progress,3);setCount(Math.round(value*eased));if(progress<1)frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick)},{threshold:.45});observer.observe(node);return()=>{observer.disconnect();cancelAnimationFrame(frame)}},[value]);const rendered=pad?String(count).padStart(Number(pad),"0"):String(count);return <article className="studio-score" ref={host}><strong>{rendered}{suffix}</strong><span>{label}</span></article>}

function ProcessCard({n,tag,title,text}:{n:string;tag:string;title:string;text:string}){const unit=useRef<HTMLElement>(null);const x=useMotionValue(0),y=useMotionValue(0);return <article className="liquid-process-unit" ref={unit}><div className="liquid-unit-skin" aria-hidden><i className="liquid-unit-card"/><motion.i className="liquid-unit-tab" style={{x,y}}/></div><div className="liquid-process-copy"><b>{n}</b><h3>{title}</h3><p>{text}</p></div><motion.div className="liquid-tab-handle" drag dragConstraints={unit} dragElastic={.12} dragMomentum={false} style={{x,y}} role="button" tabIndex={0} aria-label={`Sposta ${tag}`} whileDrag={{scale:1.06,cursor:"grabbing"}}>{tag}</motion.div></article>}

function StackedServices({lang}:{lang:Lang}){const deck=useRef<HTMLDivElement>(null);useEffect(()=>{const host=deck.current;if(!host||matchMedia("(prefers-reduced-motion: reduce)").matches)return;const cards=[...host.querySelectorAll<HTMLElement>(".studio-service-pane")],contents=[...host.querySelectorAll<HTMLElement>(".studio-service-card")];let frame=0;const update=()=>{frame=0;cards.forEach((card,i)=>{const content=contents[i],next=cards[i+1];if(!content||!next){if(content)content.style.transform="";return}const pinned=96+(i+1)*42,offset=next.getBoundingClientRect().top-pinned,distance=Math.max(card.offsetHeight-pinned,1),progress=Math.max(0,Math.min(1,1-offset/distance)),end=.94+i*.025;content.style.transform=progress<.001?"":`scale(${1+(end-1)*progress})`})};const onScroll=()=>{if(!frame)frame=requestAnimationFrame(update)};update();addEventListener("scroll",onScroll,{passive:true});addEventListener("resize",onScroll);return()=>{removeEventListener("scroll",onScroll);removeEventListener("resize",onScroll);cancelAnimationFrame(frame);contents.forEach(x=>x.style.transform="")}},[]);return <div className="studio-service-stack" ref={deck}>{serviceCards.map((s,i)=><div className="studio-service-pane" style={{"--service-index":i+1} as CSSProperties} key={s.n}><article className="studio-service-card"><span>{s.n}</span><h3>{s.title[lang]}</h3><p>{s.text[lang]}</p><small className="studio-service-price"><strong>{s.price}</strong></small><b>↗</b></article></div>)}</div>}

const showcaseSites=[
  {type:"restaurant",name:"Osteria Lume",kind:{it:"Ristorante",en:"Restaurant"},work:{it:"Menu · Prenotazioni · Storia",en:"Menu · Booking · Story"},result:{it:"Dal menu al tavolo, senza attriti",en:"From menu to table, without friction"},tone:"sun"},
  {type:"bar",name:"Bar Notturno",kind:{it:"Cocktail bar",en:"Cocktail bar"},work:{it:"Carta · Eventi · Orari",en:"Drinks · Events · Hours"},result:{it:"L’atmosfera si capisce subito",en:"The atmosphere is clear at a glance"},tone:"ink"},
  {type:"shop",name:"Forma",kind:{it:"Abbigliamento",en:"Clothing"},work:{it:"Catalogo · Filtri · Acquisto",en:"Catalogue · Filters · Shop"},result:{it:"Pochi gesti per trovare e scegliere",en:"A few steps to browse and choose"},tone:"mint"},
] as const;

function MiniWebsite({site,lang}:{site:(typeof showcaseSites)[number];lang:Lang}){
  const[view,setView]=useState(0);const[bag,setBag]=useState(0);
  const restaurant=lang==="it"?["Storia","Menu","Prenota"]:["Story","Menu","Book"];
  const bar=lang==="it"?["Stasera","Cocktail","Orari"]:["Tonight","Cocktails","Hours"];
  const shop=lang==="it"?["Novità","Donna","Uomo"]:["New in","Women","Men"];
  const labels=site.type==="restaurant"?restaurant:site.type==="bar"?bar:shop;
  return <div className={`mini-site mini-site-${site.type}`}>
    <nav><b>{site.name}</b><div>{labels.map((label,index)=><button key={label} className={view===index?"is-active":""} onClick={()=>setView(index)}>{label}</button>)}</div>{site.type==="shop"&&<button className="mini-bag" aria-label={lang==="it"?`Carrello, ${bag} articoli`:`Bag, ${bag} items`}>Bag {bag}</button>}</nav>
    {site.type==="restaurant"&&<div className="mini-scene restaurant-scene"><small>{view===0?(lang==="it"?"CUCINA SICILIANA CONTEMPORANEA":"CONTEMPORARY SICILIAN KITCHEN"):view===1?(lang==="it"?"MENU DELLA SERA · 5 PORTATE":"EVENING MENU · 5 COURSES"):(lang==="it"?"UN TAVOLO, QUESTA SERA":"A TABLE, TONIGHT")}</small><h3>{view===0?(lang==="it"?"La Sicilia, servita senza nostalgia.":"Sicily, served without nostalgia."):view===1?(lang==="it"?"Materia prima. Fuoco. Tempo.":"Ingredients. Fire. Time."):(lang==="it"?"Quanti siete?":"How many of you?")}</h3><button onClick={()=>setView((view+1)%3)}>{view===2?(lang==="it"?"2 persone · 20:30":"2 guests · 8:30 pm"):(lang==="it"?"Scopri":"Explore")} <span>→</span></button><i className="mini-plate"/></div>}
    {site.type==="bar"&&<div className="mini-scene bar-scene"><small>VIA ROMA · 18:00—02:00</small><h3>{view===0?(lang==="it"?"Il primo drink cambia la serata.":"The first drink changes the night."):view===1?"Negroni 7 · €10":(lang==="it"?"Aperti fino a tardi.":"Open until late.")}</h3><div className="mini-bar-actions"><button onClick={()=>setView(1)}>{lang==="it"?"Apri la carta":"See the menu"}</button><button onClick={()=>setView(2)}>{lang==="it"?"Dove siamo":"Find us"}</button></div><i className="mini-glass"/></div>}
    {site.type==="shop"&&<div className="mini-scene shop-scene"><header><small>DROP / 01</small><h3>{view===0?(lang==="it"?"Essenziali, ma non anonimi.":"Essential, never anonymous."):view===1?(lang==="it"?"Tagli morbidi.":"Soft silhouettes."):(lang==="it"?"Strati quotidiani.":"Everyday layers.")}</h3></header><div className="mini-products"><i/><i/><i/></div><button className="mini-add" onClick={()=>setBag(count=>count+1)}>{lang==="it"?"Aggiungi una selezione":"Add selection"} +</button></div>}
  </div>
}

function WebsiteShowcase({lang}:{lang:Lang}){return <section className="studio-showcase"><header><div><h2>{lang==="it"?"Tre attività. Tre siti diversi.":"Three businesses. Three different websites."}</h2><p>{lang==="it"?"Mini-siti interattivi per mostrare come tono, struttura e priorità cambiano davvero tra un ristorante, un bar e un negozio di abbigliamento. Sono concept dimostrativi, non clienti né risultati inventati.":"Interactive mini-sites showing how tone, structure and priorities really change across a restaurant, a bar and a clothing shop. These are demonstrative concepts, not clients or invented results."}</p></div></header><div className="studio-showcase-list">{showcaseSites.map((site,i)=><article className={`studio-site-case tone-${site.tone}`} key={site.name}><div className="studio-site-meta"><span>0{i+1}</span><p>{site.kind[lang]}</p><small>{site.work[lang]}</small></div><div className="studio-browser-mock"><div className="browser-bar"><i/><i/><i/><span>{lang==="it"?`concept 0${i+1} · prova i pulsanti`:`concept 0${i+1} · try the controls`}</span></div><MiniWebsite site={site} lang={lang}/></div><div className="studio-site-result"><span>{lang==="it"?"OBIETTIVO":"GOAL"}</span><strong>{site.result[lang]}</strong><i>↗</i></div></article>)}</div></section>}
