"use client";

import {useEffect,useRef} from "react";

const FRAGMENTS=["field = curl(noise","z = fbm(vec3","(uv * 3.0)"," * sin(time)","warp += noise(p)"," * 0.02;","uv = gl_FragCoord"," / u_resolution;","float d = length(p"," - center);","col = mix(a, b,","gl_FragColor = vec4(","def sample(x, y):","def update(dt):"," = base.copy()","for y in range(h):","buf = np.zeros(","return arr.astype(","# clamp to the grid","// keep it in gamut"];
const PAIRS=[["#ef5b3f","#2b35c9"],["#a9a0f5","#e8722f"],["#6ee87a","#7a1f14"],["#4ba3f0","#d8f0ff"],["#2b35c9","#f5d93a"],["#1e4620","#7de88a"],["#f07838","#a9a0f5"],["#f5d93a","#c2381f"],["#c94fa8","#f5e86e"],["#2fa88a","#f2b5d4"],["#5b45d9","#79e8c4"]];
const ROWS=22;

export function CodeTrailRibbon(){const host=useRef<HTMLDivElement>(null);useEffect(()=>{const el=host.current;if(!el)return;const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;const rows=[...el.querySelectorAll<HTMLElement>(".trail-row")];let w=el.clientWidth,h=el.clientHeight,font=Math.max(10,w/42),line=font*1.24,step=line*1.4,head={x:w*.7,y:h*.2},lastPush={...head},pointer=false,onScreen=false,raf=0,last=0,run=0;const pos=rows.map((_,i)=>({x:head.x-i*step,y:head.y+i*line}));
    const paint=()=>rows.forEach((row,i)=>{row.style.transform=`translate3d(${pos[i].x}px,${pos[i].y}px,0)`;row.style.opacity=String(Math.max(0,1-Math.max(0,(i/ROWS-.62)/.38)**1.6));row.style.zIndex=String(ROWS-i)});
    const resize=()=>{w=el.clientWidth;h=el.clientHeight;font=Math.max(10,w/42);line=font*1.24;step=line*1.4;el.style.setProperty("--trail-font",`${font}px`);el.style.setProperty("--trail-line",`${line}px`)};
    const frame=(now:number)=>{const dt=last?Math.min(64,now-last):16;last=now;if(!pointer){const t=now*.00018;head={x:w*(.5+.3*Math.sign(Math.sin(t))*.82),y:h*(.5+.25*Math.sign(Math.cos(t*.67))*.82)}}for(let i=0;i<rows.length;i++){const target=i?{x:pos[i-1].x-step,y:pos[i-1].y+line}:head;const k=.34-(i/(ROWS-1))*.18;pos[i].x+=(target.x-pos[i].x)*k;pos[i].y+=(target.y-pos[i].y)*k}if(Math.hypot(head.x-lastPush.x,head.y-lastPush.y)>w*.055){lastPush={...head};const tail=pos.pop()!;pos.unshift({...head});rows.unshift(rows.pop()!)}paint();if(run)raf=requestAnimationFrame(frame)};
    const sync=()=>{const should=onScreen&&!document.hidden&&!reduced;if(should&&!run){run=1;last=0;raf=requestAnimationFrame(frame)}else if(!should&&run){run=0;cancelAnimationFrame(raf)}};const move=(e:PointerEvent)=>{const r=el.getBoundingClientRect();pointer=true;head={x:e.clientX-r.left,y:e.clientY-r.top}};const leave=()=>{pointer=false};const io=new IntersectionObserver(es=>{onScreen=es.some(e=>e.isIntersecting);sync()},{rootMargin:"150px"});const ro=new ResizeObserver(()=>resize());const vis=()=>sync();resize();paint();io.observe(el);ro.observe(el);el.addEventListener("pointermove",move);el.addEventListener("pointerleave",leave);document.addEventListener("visibilitychange",vis);return()=>{run=0;cancelAnimationFrame(raf);io.disconnect();ro.disconnect();el.removeEventListener("pointermove",move);el.removeEventListener("pointerleave",leave);document.removeEventListener("visibilitychange",vis)}},[]);
  return <div className="code-trail-ribbon" ref={host} role="img" aria-label="A ribbon of colourful code fragments follows the pointer">{Array.from({length:ROWS},(_,i)=><div className="trail-row" key={i}>{Array.from({length:i===0?1:i===1?2:3},(_,j)=>{const pair=PAIRS[(i*5+j)%PAIRS.length],text=FRAGMENTS[(i*3+j)%FRAGMENTS.length];return <span key={j} style={{background:pair[0],color:pair[1],textDecoration:(i*3+j)%7===0?"underline":"none"}}>{text}</span>})}</div>)}</div>}
