import{STICKERS,type StickerDef}from"./stickers";import{renderSticker}from"./sticker-render";
const FRICTION=.92,BOUNCE=.55,MIN_VEL=.05,THROW_SCALE=.7,GRAB_SCALE=1.12,SCALE_EASE=.12,DRAG_EASE=.1,APPEAR_EASE=.09,APPEAR_STAGGER_MS=140;
type Item={def:StickerDef;art:HTMLCanvasElement;w:number;h:number;x:number;y:number;tx:number;ty:number;vx:number;vy:number;scale:number;rot:number;vr:number;dragging:boolean;peel:number;grabU:number;grabV:number;appear:number;appearAt:number;filterSvg:SVGSVGElement;displacement:SVGFEDisplacementMapElement;filterId:string};
export class WordStickers{
  private items:Item[]=[];private W=1;private H=1;private hostPageTop=0;private raf=0;private running=false;private started=false;private disposed=false;private drag:{item:Item;dx:number;dy:number;lastX:number;lastY:number;pointerId:number}|null=null;private ro?:ResizeObserver;private cleanup:(()=>void)[]=[];
  constructor(private host:HTMLElement){this.measure();for(const def of STICKERS)this.add(def);this.ro=new ResizeObserver(()=>this.onResize());this.ro.observe(host)}
  private measure(){this.W=this.host.clientWidth||1;this.H=this.host.clientHeight||1;this.hostPageTop=this.host.getBoundingClientRect().top+scrollY}
  private fontPx(){return Math.max(27,Math.min(52,(this.W>40?this.W:640)*.067))}
  private makeCrumpleFilter(seed:number){const ns="http://www.w3.org/2000/svg",svg=document.createElementNS(ns,"svg"),filter=document.createElementNS(ns,"filter"),noise=document.createElementNS(ns,"feTurbulence"),displacement=document.createElementNS(ns,"feDisplacementMap"),id=`sticker-crumple-${seed}-${Math.random().toString(36).slice(2)}`;Object.assign(svg.style,{position:"absolute",width:"0",height:"0",pointerEvents:"none"});filter.setAttribute("id",id);filter.setAttribute("x","-25%");filter.setAttribute("y","-25%");filter.setAttribute("width","150%");filter.setAttribute("height","150%");noise.setAttribute("type","fractalNoise");noise.setAttribute("baseFrequency",".018 .075");noise.setAttribute("numOctaves","2");noise.setAttribute("seed",String(seed+3));noise.setAttribute("result","wrinkles");displacement.setAttribute("in","SourceGraphic");displacement.setAttribute("in2","wrinkles");displacement.setAttribute("scale","0");displacement.setAttribute("xChannelSelector","R");displacement.setAttribute("yChannelSelector","B");filter.append(noise,displacement);svg.appendChild(filter);this.host.appendChild(svg);return{svg,displacement,id}}
  private add(def:StickerDef){const r=renderSticker({word:def.word,font:def.font,weight:def.weight,fill:def.fill,outline:def.outline,fontSizePx:this.fontPx()}),crumple=this.makeCrumpleFilter(this.items.length);const art=r.canvas;Object.assign(art.style,{position:"absolute",width:`${r.width}px`,height:`${r.height}px`,left:"0",top:"0",cursor:"grab",touchAction:"none",imageRendering:"pixelated",filter:"none",willChange:"transform,filter",transformStyle:"preserve-3d"});art.setAttribute("aria-label",def.word);this.host.appendChild(art);const it:Item={def,art,w:r.width,h:r.height,x:def.x*this.W-r.width/2,y:def.y*this.H-r.height/2,tx:0,ty:0,vx:0,vy:0,scale:1,rot:def.rot,vr:0,dragging:false,peel:0,grabU:.5,grabV:.5,appear:0,appearAt:0,filterSvg:crumple.svg,displacement:crumple.displacement,filterId:crumple.id};it.tx=it.x;it.ty=it.y;this.clamp(it);this.place(it);this.items.push(it);this.bind(it)}
  private place(it:Item){const a=it.appearAt?it.appear:1,s=it.scale*a,edge=Math.max(Math.abs(it.grabU-.5),Math.abs(it.grabV-.5))*2,rx=(.5-it.grabV)*(34+20*edge)*it.peel,ry=(it.grabU-.5)*(42+24*edge)*it.peel,skew=(it.grabU-.5)*7*it.peel,lift=it.peel*(12+5*edge),sx=1-it.peel*.025,sy=1+it.peel*.012,crumple=it.peel*(4+3*edge),shadowAlpha=.44*it.peel;it.displacement.setAttribute("scale",crumple.toFixed(2));it.art.style.transformOrigin=`${it.grabU*100}% ${it.grabV*100}%`;it.art.style.transform=`translate3d(${it.x}px,${it.y-lift}px,${lift}px) perspective(420px) rotateX(${rx}deg) rotateY(${ry}deg) skewX(${skew}deg) scaleX(${sx}) scaleY(${sy}) scale(${s})`;it.art.style.filter=`${it.peel>.015?`url(#${it.filterId}) `:""}drop-shadow(${(it.grabU-.5)*-10*it.peel}px ${2+it.peel*21}px ${2+it.peel*13}px rgba(0,0,0,${shadowAlpha})) brightness(${1+it.peel*.025}) saturate(${1+it.peel*.035})`}
  private clamp(it:Item){const r=this.host.getBoundingClientRect(),minX=-r.left+12,maxX=innerWidth-r.left-it.w-12,minY=-this.hostPageTop+12,maxY=this.H-it.h;it.x=Math.max(minX,Math.min(maxX,it.x));it.y=Math.max(minY,Math.min(maxY,it.y));it.tx=it.x;it.ty=it.y}
  private bind(it:Item){const down=(e:PointerEvent)=>{e.preventDefault();this.host.appendChild(it.art);it.dragging=true;it.vx=it.vy=0;it.art.style.cursor="grabbing";it.art.style.willChange="transform,filter";const r=this.host.getBoundingClientRect(),localX=e.clientX-r.left-it.x,localY=e.clientY-r.top-it.y;it.grabU=Math.max(0,Math.min(1,localX/it.w));it.grabV=Math.max(0,Math.min(1,localY/it.h));this.drag={item:it,dx:localX,dy:localY,lastX:e.clientX,lastY:e.clientY,pointerId:e.pointerId};it.art.setPointerCapture(e.pointerId);this.wake()};const move=(e:PointerEvent)=>{if(this.drag?.item!==it)return;const r=this.host.getBoundingClientRect();it.tx=e.clientX-r.left-this.drag.dx;it.ty=e.clientY-r.top-this.drag.dy;this.drag.lastX=e.clientX;this.drag.lastY=e.clientY};const up=(e:PointerEvent)=>{if(this.drag?.item!==it)return;it.dragging=false;it.art.style.cursor="grab";it.x=it.tx;it.y=it.ty;this.clamp(it);it.vx=it.vy=it.vr=0;it.art.releasePointerCapture?.(e.pointerId);this.drag=null;this.wake()};it.art.addEventListener("pointerdown",down);it.art.addEventListener("pointermove",move);it.art.addEventListener("pointerup",up);it.art.addEventListener("pointercancel",up);this.cleanup.push(()=>{it.art.removeEventListener("pointerdown",down);it.art.removeEventListener("pointermove",move);it.art.removeEventListener("pointerup",up);it.art.removeEventListener("pointercancel",up)})}
  private onResize(){const pw=this.W;this.W=this.host.clientWidth||1;this.H=this.host.clientHeight||1;const sx=this.W/(pw||1);for(const it of this.items){if(it.y>=0)it.x*=sx;this.clamp(it);this.place(it)}}
  private wake(){if(this.running||this.disposed||document.hidden)return;this.running=true;this.raf=requestAnimationFrame(this.loop)}
  start(){if(this.started||this.disposed){this.wake();return}const order=[...this.items].sort((a,b)=>a.def.x-b.def.x),t0=performance.now()+150;order.forEach((it,i)=>it.appearAt=t0+i*APPEAR_STAGGER_MS);this.started=true;this.wake()}
  pause(){this.running=false;cancelAnimationFrame(this.raf);this.raf=0}
  resume(){if(this.started)this.wake();else this.start()}
  private loop=(now:number)=>{if(!this.running)return;let active=Boolean(this.drag);for(const it of this.items){if(it.appearAt&&it.appear<1){active=true;if(now>=it.appearAt){it.appear+=(1-it.appear)*APPEAR_EASE;if(it.appear>.999)it.appear=1}}const target=it.dragging?GRAB_SCALE:1;it.scale+=(target-it.scale)*SCALE_EASE;it.peel+=(Number(it.dragging)-it.peel)*.1;if(Math.abs(target-it.scale)>.002||Math.abs(Number(it.dragging)-it.peel)>.002)active=true;if(it.dragging){const nx=it.x+(it.tx-it.x)*DRAG_EASE,ny=it.y+(it.ty-it.y)*DRAG_EASE;it.vx=nx-it.x;it.vy=ny-it.y;it.x=nx;it.y=ny;this.place(it);continue}const moving=Math.abs(it.vx)>=MIN_VEL||Math.abs(it.vy)>=MIN_VEL||Math.abs(it.vr)>=.01;if(moving){active=true;it.x+=it.vx;it.y+=it.vy;it.rot+=it.vr;if(it.x<0){it.x=0;it.vx=-it.vx*BOUNCE}else if(it.x>this.W-it.w){it.x=this.W-it.w;it.vx=-it.vx*BOUNCE}if(it.y<0){it.y=0;it.vy=-it.vy*BOUNCE}else if(it.y>this.H-it.h){it.y=this.H-it.h;it.vy=-it.vy*BOUNCE}it.vx*=FRICTION;it.vy*=FRICTION;it.vr*=FRICTION}this.place(it);if(!active)it.art.style.willChange="auto"}if(active&&!document.hidden)this.raf=requestAnimationFrame(this.loop);else{this.running=false;this.raf=0}};
  renderStill(){for(const it of this.items){it.appear=1;it.appearAt=1;it.vx=it.vy=it.vr=0;it.scale=1;it.peel=0;this.place(it)}}
  destroy(){this.disposed=true;this.pause();this.ro?.disconnect();this.cleanup.forEach(fn=>fn());this.items.forEach(it=>{it.art.remove();it.filterSvg.remove()})}
}
