import type {CSSProperties} from "react";
import {SquircleBox,SquircleLink} from "@/components/squircle/SquircleControl";
import type {CaseStudy} from "@/data/case-studies";

export function CaseStudyTemplate({study}:{study:CaseStudy}){const vars={"--cs-bg":study.theme.background,"--cs-surface":study.theme.surface,"--cs-ink":study.theme.ink,"--cs-muted":study.theme.muted,"--cs-accent":study.theme.accent,"--cs-accent-ink":study.theme.accentInk,"--cs-display":study.theme.fontDisplay,"--cs-body":study.theme.fontBody} as CSSProperties;return <main className="case-study" style={vars}>
  <nav className="case-nav"><span>PRR / CASE STUDY</span>{study.website?<SquircleLink href={study.website}>Visita il sito ↗</SquircleLink>:<i/>}</nav>
  <header className="case-hero"><p>{study.eyebrow}</p><h1>{study.title}</h1><strong>{study.summary}</strong><dl><div><dt>Anno</dt><dd>{study.year}</dd></div><div><dt>Ruolo</dt><dd>{study.role}</dd></div><div><dt>Servizi</dt><dd>{study.services.join(" · ")}</dd></div></dl></header>
  {study.focus!=="product"&&<section className="case-logo-stage"><SquircleBox className="case-logo-surface">{study.logo?<img src={study.logo} alt={study.logoAlt||`${study.title} logo`}/>:<div><span>LOGO</span><small>/case-studies/{study.slug}/logo.svg</small></div>}</SquircleBox></section>}
  <section className="case-narrative"><article><span>01 / SFIDA</span><h2>{study.challenge.title}</h2><p>{study.challenge.body}</p></article><article><span>02 / SOLUZIONE</span><h2>{study.solution.title}</h2><p>{study.solution.body}</p></article></section>
  {study.focus==="product"&&study.productSystem?<section className="case-section case-product-system"><header><span>03</span><h2>Dentro il progetto</h2><p>Idea, tecnologia e linguaggio dell’interfaccia: qui conta come funziona il sistema, non la costruzione di un marchio.</p></header><div>{study.productSystem.map(item=><SquircleBox className="case-product-tile" key={item.label}><i className={item.icon}/><small>{item.label}</small><h3>{item.title}</h3><p>{item.body}</p></SquircleBox>)}</div></section>:<section className="case-section case-logo-study"><header><span>03</span><h2>Studio del logo</h2><p>Segno, costruzione e capacità del marchio di vivere in contesti diversi.</p></header><div>{study.logoStudy.map((item,index)=><SquircleBox className="case-logo-tile" key={`${item.label}-${index}`}>{item.src?<img src={item.src} alt={item.label}/>:<div className="case-image-placeholder"><b>LOGO STUDY {String(index+1).padStart(2,"0")}</b><small>Aggiungi un’immagine nel file di configurazione</small></div>}<footer><strong>{item.label}</strong>{item.note&&<p>{item.note}</p>}</footer></SquircleBox>)}</div></section>}
  <section className="case-section case-brand-system"><header><span>04</span><h2>Sistema visivo</h2></header><div className="case-palette">{study.palette.map(color=><article style={{background:color.hex,color:contrast(color.hex)}} key={color.hex}><strong>{color.name}</strong><span>{color.hex}</span></article>)}</div><div className="case-type-grid">{study.typography.map(type=><article key={type.name}><small>{type.name} · {type.usage}</small><p>{type.sample}</p></article>)}</div></section>
  <section className="case-section case-screens"><header><span>05</span><h2>Pagine e dettagli</h2><p>Sostituisci i placeholder con screenshot WebP, PNG o JPG nel file di configurazione.</p></header><div>{study.screenshots.map((shot,index)=><figure className={`case-screen ${shot.size||"standard"}`} key={`${shot.caption}-${index}`}>{shot.src?<img src={shot.src} alt={shot.alt}/>:<div className="case-image-placeholder"><b>SCREENSHOT {String(index+1).padStart(2,"0")}</b><small>Consigliato: immagine ad alta risoluzione</small></div>}<figcaption><span>{String(index+1).padStart(2,"0")}</span>{shot.caption}</figcaption></figure>)}</div></section>
  <section className="case-outcome"><span>06 / RISULTATO</span><h2>{study.outcome.title}</h2><p>{study.outcome.body}</p><ul>{study.outcome.points.map(point=><li key={point}>{point}</li>)}</ul></section>
  <footer className="case-footer"><span>Fine del case study</span><h2>Il prossimo progetto<br/>è già in griglia.</h2><SquircleLink href="/gallery">Tutti i progetti →</SquircleLink></footer>
</main>}

function contrast(hex:string){const clean=hex.replace("#","");const value=clean.length===3?clean.split("").map(x=>x+x).join(""):clean;const r=parseInt(value.slice(0,2),16),g=parseInt(value.slice(2,4),16),b=parseInt(value.slice(4,6),16);return(r*299+g*587+b*114)/1000>150?"#171717":"#fff"}
