import {SarcophagusModelStudy} from "./SarcophagusModelStudy";
import type {CSSProperties} from "react";
import {SquircleLink} from "@/components/squircle/SquircleControl";
import type {CaseStudy} from "@/data/case-studies";

export function CaseStudyTemplate({study,lang="it"}:{study:CaseStudy;lang?:"it"|"en"}) {
  const t=(it:string,en:string)=>lang==="en"?en:it;
  const vars={"--cs-bg":study.theme.background,"--cs-surface":study.theme.surface,"--cs-ink":study.theme.ink,"--cs-muted":study.theme.muted,"--cs-accent":study.theme.accent,"--cs-accent-ink":contrast(study.theme.accent),"--cs-display":study.theme.fontDisplay,"--cs-body":study.theme.fontBody} as CSSProperties;
  return <main className={`case-study case-study-refined case-${study.slug}`} style={vars} lang={lang}>
    <nav className="case-nav" aria-label={t("Navigazione progetto","Project navigation")}><SquircleLink className="gallery-back case-back" href="/gallery"><i className="fa-solid fa-arrow-left" aria-hidden="true"/>{t("Progetti","Projects")}</SquircleLink><span>{t("Paolo Pirruccio / Studio di progetto","Paolo Pirruccio / Case study")}</span>{study.website?<SquircleLink className="case-project-action" href={study.website}>{t("Apri il progetto","Open project")} <i className="fa-solid fa-arrow-up-right-from-square" aria-hidden="true"/></SquircleLink>:<span>{t("Progetto grafico","Graphic design project")}</span>}</nav>
    <header className="case-hero"><p>{study.eyebrow}</p><h1>{study.title}</h1><strong>{study.summary}</strong><dl>{study.context&&<div><dt>{t("Contesto","Context")}</dt><dd>{study.context}</dd></div>}{study.year&&<div><dt>{t("Anno","Year")}</dt><dd>{study.year}</dd></div>}<div><dt>{t("Contributo","Contribution")}</dt><dd>{study.role}</dd></div><div><dt>{t("Ambiti","Areas")}</dt><dd>{study.services.join(" · ")}</dd></div>{study.status&&<div><dt>{t("Stato","Status")}</dt><dd>{study.status}</dd></div>}</dl></header>
    {study.screenshots[0]?.src&&<figure className="case-opening"><img src={study.screenshots[0].src} alt={study.screenshots[0].alt}/><figcaption>{study.screenshots[0].caption}</figcaption></figure>}
    <section className="case-narrative"><article><span>{t("01 / Il punto di partenza","01 / The starting point")}</span><h2>{study.challenge.title}</h2><p>{study.challenge.body}</p></article><article><span>{t("02 / Il progetto","02 / The project")}</span><h2>{study.solution.title}</h2><p>{study.solution.body}</p></article></section>
    {study.slug==="sarcofago-tebanianus"&&<SarcophagusModelStudy lang={lang}/>}
    {study.logoStudy.some(item=>item.src)&&<section className="case-section case-logo-study"><header><span>03</span><h2>{study.visualTitle||t("Segni e dettagli","Marks and details")}</h2><p>{study.visualIntro}</p></header><div>{study.logoStudy.filter(item=>item.src).map(item=><figure className="case-logo-tile" key={item.label}><div className={`case-asset ${item.detail||""}`}><img src={item.src} alt={item.label} loading="lazy"/></div><figcaption><strong>{item.label}</strong>{item.note&&<p>{item.note}</p>}</figcaption></figure>)}</div></section>}
    <section className="case-section case-brand-system"><header><span>04</span><h2>{t("Colori e caratteri","Colours and typefaces")}</h2><p>{study.paletteNote}</p></header><div className="case-palette">{study.palette.map(color=><article style={{background:color.hex,color:contrast(color.hex)}} key={color.hex}><strong>{color.name}</strong><span>{color.hex}</span></article>)}</div><div className="case-type-grid">{study.typography.map((type,index)=><article key={type.name}><small>{type.name} · {type.usage}</small><p style={{fontFamily:study.slug==='astergift'?(index===0?study.theme.fontDisplay:study.theme.fontBody):`"${type.name}", ${index===2?'monospace':'sans-serif'}`}}>{type.sample}</p></article>)}</div>{study.typeNote&&<p className="case-source-note">{study.typeNote}</p>}</section>
    {study.process&&<section className="case-section case-process"><header><span>05</span><h2>{t("Dentro il lavoro","Inside the work")}</h2></header><div>{study.process.map((item,index)=><article key={item.title}><span>{String(index+1).padStart(2,"0")}</span><h3>{item.title}</h3><p>{item.body}</p></article>)}</div></section>}
    {study.screenshots.slice(1).some(shot=>shot.src)&&<section className="case-section case-screens"><header><span>06</span><h2>{study.slug==="astergift"?t("Applicazioni su carta e schermo","Applications in print and on screen"):t("Il progetto sullo schermo","The project on screen")}</h2></header><div>{study.screenshots.slice(1).filter(shot=>shot.src).map(shot=><figure className="case-screen" key={shot.caption}><img src={shot.src} alt={shot.alt} loading="lazy"/><figcaption>{shot.caption}</figcaption></figure>)}</div></section>}
    <section className="case-outcome"><span>{t("Cosa mi porto dal progetto","What I take from the project")}</span><h2>{study.outcome.title}</h2><p>{study.outcome.body}</p><ul>{study.outcome.points.map(point=><li key={point}>{point}</li>)}</ul></section>
    <footer className="case-footer"><span>{t("Paolo Pirruccio / Portfolio","Paolo Pirruccio / Portfolio")}</span><h2>{t("Altri progetti,","More projects,")}<br/>{t("altre prove.","more experiments.")}</h2><SquircleLink href="/gallery">{t("Torna ai progetti","Back to projects")} <i className="fa-solid fa-table-cells-large" aria-hidden="true"/></SquircleLink></footer>
  </main>;
}
function contrast(hex:string){const clean=hex.replace("#","");const value=clean.length===3?clean.split("").map(x=>x+x).join(""):clean;const rgb=[0,2,4].map(i=>parseInt(value.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:Math.pow((v+.055)/1.055,2.4));return rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722>.179?"#000000":"#ffffff";}
