"use client";

import {animate,useAnimationFrame,useMotionValue,useReducedMotion} from "motion/react";
import {useEffect,useRef} from "react";

export function ElasticSeparator({label="Separatore elastico"}:{label?:string}){
  const host=useRef<SVGSVGElement>(null),path=useRef<SVGPathElement>(null),dragging=useRef(false),moved=useRef(false),startY=useRef(0),tapOnly=useRef(false),width=useMotionValue(1),x=useMotionValue(.5),y=useMotionValue(0),reduced=useReducedMotion();
  useEffect(()=>{const svg=host.current;if(!svg)return;const media=matchMedia("(max-width: 768px), (pointer: coarse)"),updateMode=()=>tapOnly.current=media.matches,update=()=>width.set(svg.getBoundingClientRect().width||1);updateMode();update();media.addEventListener("change",updateMode);const observer=new ResizeObserver(update);observer.observe(svg);return()=>{media.removeEventListener("change",updateMode);observer.disconnect()}},[width]);
  useAnimationFrame(()=>{const w=width.get(),cx=Math.max(0,Math.min(w,x.get())),cy=36+y.get();path.current?.setAttribute("d",`M0 36 Q${cx} ${cy} ${w} 36`)});
  const release=(pointerId?:number)=>{if(!dragging.current)return;dragging.current=false;const svg=host.current;if(pointerId!==undefined&&svg?.hasPointerCapture(pointerId))svg.releasePointerCapture(pointerId);const w=width.get();if(!reduced&&!moved.current){y.set(startY.current<=36?16:-16)}animate(x,w/2,{type:"spring",stiffness:250,damping:16});animate(y,0,reduced?{duration:0}:{type:"spring",stiffness:225,damping:5.8,mass:.58})};
  const pulse=(clientX?:number)=>{if(reduced)return;const rect=host.current?.getBoundingClientRect();x.set(rect&&clientX!==undefined?clientX-rect.left:width.get()/2);y.set(18);animate(x,width.get()/2,{type:"spring",stiffness:250,damping:16});animate(y,0,{type:"spring",stiffness:225,damping:5.8,mass:.58})};
  return <svg ref={host} className="elastic-separator" role="button" aria-label={label} tabIndex={0} preserveAspectRatio="none" onClick={event=>{if(tapOnly.current)pulse(event.clientX)}} onPointerDown={event=>{if(tapOnly.current)return;const rect=event.currentTarget.getBoundingClientRect();dragging.current=true;moved.current=false;startY.current=event.clientY-rect.top;x.set(event.clientX-rect.left);event.currentTarget.setPointerCapture(event.pointerId)}} onPointerMove={event=>{if(tapOnly.current||!dragging.current)return;const rect=event.currentTarget.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom){release(event.pointerId);return}const offset=event.clientY-rect.top-36;moved.current=moved.current||Math.abs(offset)>4;x.set(event.clientX-rect.left);y.set(Math.max(-54,Math.min(54,offset*1.35)))}} onPointerLeave={event=>{if(!tapOnly.current)release(event.pointerId)}} onPointerUp={event=>{if(!tapOnly.current)release(event.pointerId)}} onPointerCancel={event=>{if(!tapOnly.current)release(event.pointerId)}} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();pulse()}}}><path ref={path} fill="none" vectorEffect="non-scaling-stroke"/></svg>
}
