export function SarcophagusModelStudy({lang="it"}:{lang?:"it"|"en"}){
  const t=(it:string,en:string)=>lang==="en"?en:it;
  return <section className="case-section case-model-analysis" id="il-modello" aria-labelledby="model-study-title">
    <header><span>{t("Il reperto","The artifact")}</span><h2 id="model-study-title">{t("Leggere il modello","Reading the model")}</h2><p>{t("Prima del racconto e dei comandi, c’è l’oggetto. Questa vista del modello originale permette di soffermarsi sulla struttura del sarcofago e sul ritmo del suo rilievo.","Before the story and the controls comes the object. This view of the original model lets visitors pause over the sarcophagus structure and the rhythm of its relief.")}</p></header>
    <figure className="case-model-figure">
      <iframe src="/3D/model-study.html" title={t("Modello originale del Sarcofago Tebanianus, inquadratura fissa","Original Tebanianus Sarcophagus model, fixed view")} loading="lazy" tabIndex={-1}/>
      <figcaption><span>{t("Modello fotogrammetrico preparato in MeshLab e Blender, caricato in formato Nexus e presentato qui con una vista fissa.","Photogrammetric model prepared in MeshLab and Blender, loaded in Nexus format and shown here in a fixed view.")}</span><a href="/3D/index.html#esplora">{t("Esplora il modello nel sito","Explore the model on the website")} <i className="fa-solid fa-arrow-up-right-from-square" aria-hidden="true"/></a></figcaption>
    </figure>
    <div className="case-model-notes">
      <article><span>{t("01 / struttura","01 / Structure")}</span><h3>{t("Una cornice per il rilievo.","A frame for the relief.")}</h3><p>{t("Il bordo superiore modanato e la base delimitano il campo figurato. Le linee orizzontali tengono insieme la composizione, mentre le figure e i festoni sporgono dalla superficie e ne interrompono la regolarità.","The moulded upper edge and the base define the figurative field. Horizontal lines hold the composition together, while figures and garlands project from the surface and interrupt its regularity.")}</p></article>
      <article><span>{t("02 / composizione","02 / Composition")}</span><h3>{t("Il ritmo dei festoni.","The rhythm of the garlands.")}</h3><p>{t("I festoni carichi di frutti e foglie disegnano ampie curve sul fronte. Le figure che li sostengono scandiscono la superficie; nei campi tra le curve trovano posto altre scene. Ho usato questa suddivisione per organizzare le tappe della lettura guidata.","Garlands laden with fruit and leaves form broad curves across the front. The figures supporting them divide the surface; other scenes occupy the spaces between the curves. I used this arrangement to organise the stages of the guided reading.")}</p></article>
      <article><span>{t("03 / superficie","03 / Surface")}</span><h3>{t("Un oggetto con le sue tracce.","An object bearing its traces.")}</h3><p>{t("La superficie chiara presenta differenze di tono, bordi irregolari e dettagli più o meno leggibili. Il modello conserva queste variazioni: osservarle aiuta a distinguere la forma generale dai particolari del rilievo, senza ridurre il reperto a una sagoma uniforme.","The light surface has variations in tone, irregular edges and details of varying clarity. The model preserves these differences: observing them helps distinguish the overall form from the details of the relief, without reducing the artifact to a uniform shape.")}</p></article>
      <article><span>{t("04 / dal volume al segno","04 / From volume to line")}</span><h3>{t("Cosa rende visibile il 3D.","What 3D makes visible.")}</h3><p>{t("La profondità separa figure, festoni e fondo. I disegni SVG mostrati nello studio isolano invece i contorni. Nel sito ho affiancato questi due modi di osservare lo stesso oggetto: il modello restituisce il volume, il tratto aiuta a seguire una scena.","Depth separates figures, garlands and background. The SVG drawings shown in the study instead isolate the outlines. On the website, I placed these two ways of observing the same object side by side: the model conveys volume, while the linework helps the viewer follow a scene.")}</p></article>
    </div>
  </section>;
}
